services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      #- "8080:8080"  # Para el dashboard de Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - webnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`64.23.166.216`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"

  shiny-app:
    build: 
      context: .
      dockerfile: dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shiny.rule=Host(`64.23.166.216`)"
      - "traefik.http.routers.shiny.entrypoints=web"
      - "traefik.http.services.shiny.loadbalancer.server.port=3838"
    depends_on:
      - traefik
    networks:
      - webnet

networks:
  webnet:
    driver: bridge